import Head from "next/head";
import {
  PlayCircleIcon,
  CheckIcon,
  PlusIcon,
} from "@heroicons/react/24/outline";
import { GetStaticProps, NextPage } from "next";
import Link from "next/link";
import Image from "next/image";
import { GdBadge } from "../components/badges";
import { GdButton } from "../components/buttons";
import GdDisclosure from "../components/disclosures";
import { Course, Section } from "../types";

import { getCourseInfo, getAllSections } from "../services";

export interface HomePageProps {
  course: Course;
  sections: Array<Section>;
}

export const getStaticProps: GetStaticProps = async () => {
  const sections: Array<Section> = await getAllSections();
  const course = getCourseInfo();

  return {
    props: {
      sections,
      course,
    },
  };
};

const HomePage: NextPage<HomePageProps> = ({ course, sections = [] }) => {
  return (
    <>
      <Head>
        <title>{course.title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon-16x16.png"
        />
        <link rel="manifest" href="/site.webmanifest" />
      </Head>

      <main>
        <section className="px-4 bg-[#ffd300]">
          <div className="max-w-5xl mx-auto py-16">
            <div className="flex gap-4">
              <GdBadge>Free</GdBadge>
              <div>Course</div>
            </div>

            <h1 className="text-4xl lg:text-5xl font-semibold mt-6 text-gray-900">
              {course.title}
            </h1>
            <p className="mt-6 text-lg w-full md:w-3/4">{course.subTitle}</p>

            <div className="mt-10">
              <GdButton>Bắt đầu ngay</GdButton>
            </div>
          </div>
        </section>

        {/* <section className="px-4 mt-12">
          <div className="max-w-5xl mx-auto flex justify-between p-8 border border-gray-500">
            <div className="flex gap-2 items-center">
              <ChartBarIcon className="h-10" />
              <div>
                <div>Skill level</div>
                <div className="font-bold">Beginner</div>
              </div>
            </div>

            <div className="flex gap-2 items-center">
              <ClockIcon className="h-10" />
              <div>
                <div>Time to complete</div>
                <div className="font-bold">Approx. 20 hours</div>
              </div>
            </div>

            <div className="flex gap-2 items-center">
              <Bars3BottomLeftIcon className="h-10" />
              <div>
                <div>Prerequisites</div>
                <div className="font-bold">None</div>
              </div>
            </div>
          </div>
        </section> */}

        {/* <section className="px-4 mt-12">
          <div className="max-w-5xl mx-auto flex justify-between p-8 rounded-md border border-gray-500">
            <h2>About this course</h2>
          </div>
        </section> */}

        <section className="px-4 mt-12">
          <div className="max-w-5xl flex flex-col lg:flex-row gap-10 mx-auto">
            <div className="lg:w-1/2">
              <h2 className="text-2xl font-medium">Tổng quan khóa học</h2>

              <p className="mt-5">{course.description}</p>
            </div>
            <div className="lg:w-1/2">
              <h2 className="text-2xl font-medium">Yêu cầu</h2>

              <ul className="mt-5 flex flex-col gap-y-3">
                {course.requiredSkills.map((skill, index) => (
                  <li className="flex " key={index}>
                    <PlusIcon className="h-6 mr-3 flex-shrink-0" />
                    <div>{skill}</div>
                  </li>
                ))}
              </ul>
            </div>
          </div>
        </section>

        <section className="px-4 mt-12">
          <div className="max-w-5xl mx-auto lg:p-8 lg:border border-gray-500">
            <h2 className="text-2xl font-medium">
              Chúng ta sẽ đạt được những gì sau khóa học này
            </h2>

            <ul className="mt-5 grid gap-x-10 gap-y-3 grid-cols-1 lg:grid-cols-2">
              {course.skills.map((skill, index) => (
                <li className="flex justify-start " key={index}>
                  <CheckIcon className="h-6 mr-3 flex-shrink-0" />
                  <div>{skill}</div>
                </li>
              ))}
            </ul>
          </div>
        </section>

        <section className="px-0 lg:px-4 mt-12">
          <div className="max-w-5xl mx-auto">
            <div className="flex justify-between items-end">
              <div className="px-4 lg:px-0">
                <h2 className="text-2xl font-medium">
                  Nội dung chi tiết khóa học
                </h2>
                {/* <div className="mt-2">
                  {sections.length} phần • 12 projects • 8 quizzes
                </div> */}
              </div>
              {/* <div className="cursor-pointer px-1 select-none rounded text-indigo-700 font-semibold hover:bg-gray-200">
                Expand all sections
              </div> */}
            </div>

            <div className="mt-4 divide-y divide-gray-500 border-t border-b lg:border border-gray-500">
              {sections.map((section) => (
                <GdDisclosure key={section.slug}>
                  <GdDisclosure.Header>
                    <h3 className="lg:text-xl font-medium lg:font-semibold">
                      {section.title}
                    </h3>
                    <p className="mt-2 font-light">{section.description}</p>
                  </GdDisclosure.Header>
                  <GdDisclosure.Content>
                    {section.lessons.map((lesson) => (
                      <div key={lesson.slug} className="pl-2 lg:pl-5 pr-2 py-3">
                        <div className="flex gap-3">
                          <PlayCircleIcon className="h-6 flex-shrink-0" />
                          <span className="flex-grow hover:text-indigo-700">
                            <Link href={lesson.fullSlug}>
                              <h4>{lesson.title}</h4>
                            </Link>
                          </span>
                          <div className="flex-shrink-0">04:30</div>
                        </div>
                      </div>
                    ))}
                  </GdDisclosure.Content>
                </GdDisclosure>
              ))}
            </div>
          </div>
        </section>

        <section className="px-4 mt-12 bg-[#10162f]">
          <div className="max-w-2xl mx-auto py-16 text-center">
            <h2 className="text-3xl lg:text-4xl font-semibold lg:leading-tight text-gray-100">
              Bạn đã sẵn sàng?
            </h2>
            <p className="mt-4 lg:text-xl font-medium lg:font-semibold lg:leading-tight text-gray-200">
              Khóa học hoàn toàn miễn phí dành cho tất cả mọi người, học mọi lúc
              mọi nơi ngay trên Youtube
            </p>

            <a
              target="_blank"
              rel="noreferrer"
              href="https://www.youtube.com/@giadinhlaptrinh"
            >
              <GdButton variant="secondary" className="mt-10">
                Xem trên Youtube
              </GdButton>
            </a>
          </div>
        </section>

        <section className="px-4 bg-[#ffd300]">
          <div className="max-w-6xl mx-auto py-16">
            <div className="flex flex-col-reverse lg:flex-row lg:justify-between lg:items-center">
              <div className="w-full lg:w-6/12 flex-shrink-0">
                <h2 className="text-3xl lg:text-4xl font-semibold lg:leading-tight text-gray-900">
                  Tham gia cùng bạn bè trên khắp thế giới và bắt đầu học
                  JavaScript ngay hôm nay
                </h2>

                <div className="text-center lg:text-left">
                  <GdButton variant="primary" wide className="mt-8">
                    Bắt đầu
                  </GdButton>
                </div>
              </div>

              <div className="w-full lg:w-5/12 mb-8 lg:mb-0 flex justify-center lg:justify-end items-center">
                <img
                  className="w-3/5"
                  src="./images/girl-enjoying-reading.png"
                  alt="Picture of the author"
                />
              </div>
            </div>
          </div>
        </section>
      </main>
    </>
  );
};

export default HomePage;
